name: Clear GitHub Pages Cache

on:
  push:
    branches:
      - main  # Se ejecuta cuando subes cambios a la rama principal

jobs:
  clear_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Purge GitHub Pages cache
        run: |
          curl -X PURGE https://alexmichalec98.github.io/Hackathon25/datos.csv
          curl -X PURGE https://alexmichalec98.github.io/Hackathon25/
